config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

  get 'home/show'
  resources :ratings, :characters, :users, :categories

  resources :user_sessions, only: [ :new, :create, :destroy ]

  get 'login'  => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'

  post '/ajax/vote' => 'ratings#ajax_vote'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"

end

app/models/character.rb
class Character < ActiveRecord::Base
  validates :character_name, presence: true, uniqueness: true

  has_many :losses,
    primary_key: :id,
    foreign_key: :loser_id,
    class_name: :Rating

  has_many :wins,
    primary_key: :id,
    foreign_key: :winner_id,
    class_name: :Rating

  def total_ratings
    wins.count + losses.count
  end

  def total_score
    win_score = wins.count * 100
    win_score / (total_ratings)
  end

  def category_wins(category_id)
    wins.where("ratings.category_id = ?", category_id).count
  end

  def category_losses(category_id)
    losses.where("ratings.category_id = ?", category_id).count
  end

  def category_score(category_id)
    w = category_wins(category_id)
    l = category_losses(category_id)
    total = l + w
    return (w * 100).fdiv(total) if total != 0
    nil
  end

  def self.random_character
    rand(self.all.length) + 1
  end

  def self.random_pair
    character1 = self.random_character
    character2 = self.random_character
    [character1, character2]
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
before_filter :require_login


  def index
    @characters = Character.all
    @categories = Category.all
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
    @character= Character.find(params[:id])
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
    @character= Character.find(params[:id])
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    @character= Character.find(params[:id])
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:character_name)
    end



  helper_method :sorted_category
  def sorted_category(category_id)
    chars = @characters.reject{|c| c.category_score(category_id).nil?}
    chars.sort_by{|c| c.category_score(category_id)}.reverse
  end



end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :character_name %><br>
    <%= f.text_field :character_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
    <% user_rating_count = current_user.ratings.count %>
    <% if user_rating_count >= 25 %>
      <div class="panel-group" id="accordion">
        <p>
          Based on <%= rating_count %> ratings made so far:
        </p>
        <% @categories[0...1].each do |cat| %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%=cat.category_name=%>">
                Alaska's <%= cat.super.capitalize %> Politicians</h1>
              </a>
            </h3>
          </div>
          <div id="collapse<%=cat.category_name=%>" class="panel-collapse collapse in">
            <div class="panel-body">
              <ol id='characters'>
                <% sorted_category(cat.id).each do |character| %>
                <li>
                  <%= character.character_name %> - <%= character.category_score(cat.id).round(1) %>
                </li>
                <% end %>
              </ol>
            </div>
          </div>
          <%end%>
          <% @categories[1..-1].each do |cat| %>
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%=cat.category_name.split.join=%>">
                  Alaska's <%= cat.super.split.map(&:capitalize).join(' ') %> Politicians</h1>
                </a>
              </h3>
            </div>
            <div id="collapse<%=cat.category_name.split.join=%>" class="panel-collapse collapse">
              <div class="panel-body">
                <ol id='characters'>
                  <% sorted_category(cat.id).each do |character| %>
                  <li>
                    <%= character.character_name %> - <%= character.category_score(cat.id).round(1) %>
                  </li>
                  <% end %>
                </ol>
              </div>
            </div>


          </div>
          <%end %>
        </div>
      </div>

    <% else %>
      <h3>You must give at least 25 ratings to view the scores!</h3>
      <h3>You currently have <%= user_rating_count %> ratings.</h3>
      <h3><%= link_to "Go rate some politicians!", ratings_path =%></h3>
    <% end %>

app/views/characters/new.html.erb
<% if current_user.admin %>

  <h1>New Character</h1>

  <%= render 'form' %>

  <%= link_to 'new character', new_character_path %> <%= link_to 'new category', new_category_path %>
  <%= link_to 'users', users_path %>

<% end %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Character name:</strong>
  <%= @character.character_name %>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>