config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

  get 'home/show'
  resources :ratings, :characters, :users, :categories

  resources :user_sessions, only: [ :new, :create, :destroy ]

  get 'login'  => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'

  post '/ajax/vote' => 'ratings#ajax_vote'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Polrater</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%=favicon_link_tag 'favicon.jpg' %>

  <meta property="og:title" content="Alaska Politician Rater" />
  <meta property="og:type" content="article" />
  <meta property="og:image" content="https://alaskapoliticianrater.herokuapp.com/assets/alaskacover.png" />
  <meta property="og:url" content="https://alaskapoliticianrater.herokuapp.com/" />
  <meta property="og:description" content="Rate Alaska politicians head to head and see how others rank your favorite (or least favorite) politicians." />
</head>

<body>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-82455013-1', 'auto');
    ga('send', 'pageview');
  </script>
  <script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '160728694357785',
      xfbml      : true,
      version    : 'v2.7'
    });
  };

  (function(d, s, id){
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) {return;}
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
  </script>

  <div id="container">
    <nav class="navbar navbar-dark bg-inverse" style="border-radius: 0px">
      <a class="navbar-brand" href="http://pauloliva.com"><%= image_tag('favicon2.jpg', width:"24") %></a>
    <ul class="nav navbar-nav">
      <li class="nav-item">
        <%= link_to 'Rate Politicians', ratings_path %>
      </li>
      <li class="nav-item">
        <%= link_to 'Scores', characters_path %>
      </li>
      <li class="nav-item">
        <%= link_to 'Headline Generator', page_path('headlines') %>
      </li>
    </ul>

    <ul class="nav navbar-nav" style="float: right">
       <li class ="nav-item">
         <% if current_user %>
         <%= "Logged in as #{current_user.name}" %>
         <%= link_to "(Logout)", logout_path %>
         <% else %>
         <%= link_to "Sign up", root_path %>
         <% end %>
         <% if current_user && current_user.admin %>
         <%= link_to 'Admin Panel', new_character_path %>
         <% end %>
       </li>
     </ul>


  </nav>



  <div id="content">
    <p class="flash"><%= flash.notice %></p>
    <div class = "row" >
      <div class = "col-md-2">

      </div>
      <div class = "col-md-8" id = "ratings" style="margin-bottom: 5px; border-style: solid; border-radius: 5px; background-color: rgba(159,159,159, 0.85)">
        <%= yield %>
      </div>
      <div class = "col-md-2">
        <!-- <p> test <p> -->
      </div>
    </div>
  </div>
  <% if current_user %>
      <footer class="footer">
      <div class="container">
          <div class="row">
              <div class="col-md-7">
                <% if current_user %>
                  <% user_rating_count = current_user.ratings.count %>
                    <h5>You've made <%=user_rating_count%> ratings!</h5>
                  <% if user_rating_count >= 25%>
                    <h5><%= link_to 'You can now view the current rankings here', characters_path %></h5>
                    <!-- <h5><i class="fa fa-road">Servers are expensive.</h5></i>
                    <a href = "https://squareup.com/store/paul-oliva"><h5>Can you chip in to help us out?</h5></a> -->
                  <% end %>
                <% end %>
                  <div class="row">
                      <div class="col-xs-6">
                      </div>
                      <div class="col-xs-6">
                          <!-- <ul class="list-unstyled">
                              <li><a href="">Documentation</a></li>
                              <li><a href="">Support</a></li>
                              <li><a href="">Legal Terms</a></li>
                              <li><a href="">About</a></li>
                          </ul> -->
                      </div>
                  </div>
                  <ul class="nav nav-inline">
                      <li class="nav-item"><a href=""><i class="fa fa-facebook fa-2x"></i></a></li>
                      <li class="nav-item"><a href=""><i class="fa fa-twitter fa-2x"></i></a></li>
                      <li class="nav-item"><a href=""><i class="fa fa-github fa-2x"></i></a></li>
                      <li class="nav-item"><a href=""><i class="fa fa-instagram fa-2x"></i></a></li>
                  </ul>
                  <br>
              </div>
              <!-- <div class="col-md-2">
              </div> -->
              <div class="col-md-5">
                <ul class="list-unstyled">
                  <li><%= link_to "FAQ", page_path('faq') %></li>
                  <li><a href="https://squareup.com/store/paul-oliva">Donate</a></li>
                  <!-- <li><a href="">Partners</a></li>
                  <li><a href="">Team</a></li> -->
                </ul>
                <hr>
                <% if current_user %>
                <%= "Logged in as #{current_user.name}" %>
                <%= link_to "(logout)", logout_path %>
                <% else %>
                <%= link_to "Login", login_path %> |
                <%= link_to "Sign up", signup_path %>
                <% end %>
                <% if current_user && current_user.admin %>
                <%= link_to 'Admin Panel', new_character_path %>
                <% end %>
                <div
                class="fb-like"
                data-share="true"
                data-width="450"
                data-show-faces="true">
              </div>

              </div>
          </div>
      </div>
  </footer>
  <% end %>

</div>
</body>
</html>